process_dir: /path/to/process/directory
shows_dir: /path/to/shows/directory
movies_dir: /path/to/movies/directory
collections_dir: /path/to/collections/directory

enable_backup: false  # set to true to enable backup and create backup folder
naming_convention: # optional: emby, jellyfin, kodi, kometa, plex

webhook_url: # discord webhook url, leave blank to disable notifications
