## Paths ##
process: /path/to/process/directory
shows: /path/to/shows/directory
movies: /path/to/movies/directory
collections: /path/to/collections/directory

## Settings ##
enable_backup: false # or true
naming_convention: # options: emby, jellyfin, kodi, kometa, plex

## Notifications ## 
# Leave blank to disable
discord_webhook: 
