process_dir: /path/to/process/directory
shows_dir: /path/to/shows/directory
movies_dir: /path/to/movies/directory
collections_dir: /path/to/collections/directory

enable_backup: false  # set to true to enable backup and create backup folder
webhook_url: # "discord_webhook_url" leave blank to disable notifications
